### ISSUE TITLE
Example how to build and run tests

### ISSUE THREAD

**Issue by chompomonim** [ModusCreateOrg/budgeting-sample-app-webpack2#1]
It would be awesome to see some simple tests for this environment.

**Comment by grgur** [comment]
@elodszopos would you care to sprinkle some of your unit test magic here?

**Comment by elodszopos** [comment]
Most definitely. Soon as I get around to it. We will have full lint, style lint and unit test support.

**Comment by grgur** [comment]
This is now scheduled for v2. Thanks.
