### ISSUE TITLE
Inconsistent Behaviour - Getting Uncaught ReferenceError: libs_dll is not defined

### ISSUE THREAD

**Issue by rajputvai** [ModusCreateOrg/budgeting-sample-app-webpack2#104]
## Description
1. I am getting _Uncaught ReferenceError: libs_dll is not defined_ on browser console sometimes when I do command + shift + r. 
2. The error is not consistent. 
3. Also compile time has been increased drastically after this commit. https://github.com/ModusCreateOrg/budgeting-sample-app-webpack2/commit/25e0d40918b88df9a8ea7e3a32b0444ae88c36e4 (This is  the commit I am using).

## Steps to reproduce
1. git clone https://github.com/ModusCreateOrg/budgeting-sample-app-webpack2.git
2. yarn install
3. yarn start
4. Open chrome and console panel
5. Access localhost:3000
6. command + shift + r multiple times after each reload
7. You will see the error.

## Expected Behaviour
1. App should run all the time even on hard refresh
2. Sub sequent compile time should be less. 

## Additional Details
1. node : v6.11.1
2. yarn version : 1.0.0
3. npm : 3.10.10
4. Chrome : Version 60.0.3112.113 (Official Build) (64-bit)

![screen shot 2017-09-15 at 12 19 23 pm](https://user-images.githubusercontent.com/2168116/30470923-554c8c12-9a14-11e7-9bc6-53cd34d96d89.png)

**Comment by grgur** [comment]
Hey @rajputvai, thanks for reporting!

It would be great if you could check this with the latest code.

1. We've improved webpack build and rebuild time significantly in https://github.com/ModusCreateOrg/budgeting-sample-app-webpack2/pull/90 (commit https://github.com/ModusCreateOrg/budgeting-sample-app-webpack2/commit/1b94393ee26435c5fed960ebb565bb3ffc72d8a4)
2. As for the intermittent DLL issue, I wonder if that's Service Worker related. Is `sw.js` registered in Chrome Dev tools -> Application -> Service Workers?

**Comment by rajputvai** [comment]
Hi @grgur, Thanks for reply,

1. Earlier rebuild time was 2-5 secs, now it is 15-25 secs. I have restarted my system and also tried. I tested on master branch of budgeting-sample-app-webpack2
2. Issue is only there in dev mode. We don't have Service Worker in dev mode, And it is happening so frequently. No issue on production build (Service Worker was connected).

**Comment by grgur** [comment]
@rajputvai this should be improved once we merge https://github.com/ModusCreateOrg/budgeting-sample-app-webpack2/pull/107
