### ISSUE TITLE
Bundling Issue

### ISSUE THREAD

**Issue by cwkummer** [ModusCreateOrg/budgeting-sample-app-webpack2#13]
It appears that this code has some of the issues discussed on this thread:

https://github.com/webpack/webpack/issues/2537

Specifically, I had to remove the -p option or the Uglify plugin ran twice. Also, -p was not setting the NODE_ENV variable, so the production parts of the webpack.config were never being run. If I manually set the NODE_ENV at the command line to 'production', it would run the production sections of the webpack.config.

Clearing the NODE_ENV (set NODE_ENV=) and running webpack (no -p) result in a 1 meg package. Even if I manually set NODE_ENV, I get a 56k (gzip/min package), which is different than your size, so I am wondering what's wrong.

**Comment by grgur** [comment]
That was fixed in the latest commit, thanks
