### ISSUE TITLE
vendor packages from package.json

### ISSUE THREAD

**Issue by anvk** [ModusCreateOrg/budgeting-sample-app-webpack2#16]
Would it be beneficial if we just add all `dependencies` from `package.json` as vendor files in 
[webpack.config.js](https://github.com/ModusCreateOrg/budgeting-sample-app-webpack2/blob/master/webpack.config.js#L57)

**Comment by grgur** [comment]
Ideally you would let webpack figure it out to leverage tree shaking. You don't want the entire module checked in sometimes.
