### ISSUE TITLE
Very high CPU usage

### ISSUE THREAD

**Issue by MikeBazhenov** [ModusCreateOrg/budgeting-sample-app-webpack2#26]
webpack --watch

With your config, webpack using 80% CPU
<img width="470" alt="2017-03-07 18 12 20" src="https://cloud.githubusercontent.com/assets/1553430/23654078/b1e1408e-0361-11e7-9be6-eb47ed836038.png">

**Comment by grgur** [comment]
We are redoing this entire example. Will let you know when V2 is shipped (should be soon)
