### ISSUE TITLE
is tree shaking done properly?

### ISSUE THREAD

**Issue by RichardIvan** [ModusCreateOrg/budgeting-sample-app-webpack2#3]
How does one know the tree shaking is done properly. In the webpack-visualizer, it seems like all of the npm packages were imported in full.

**Comment by godu** [comment]
@RichardIvan the tree-shaking is completely broken on webpack beta branch.
https://github.com/webpack/webpack/issues/2867

**Comment by grgur** [comment]
To make it easier to spot differences, I suggest you also try adding React Router to the project as it fully supports tree shaking.
