### ISSUE TITLE
Feedback

### ISSUE THREAD

**Issue by addyosmani** [ModusCreateOrg/budgeting-sample-app-webpack2#55]
Great work so far! When profiling the app on an EM connection (pretty real world 3G with accountability for spottiness) we don't see first meaningful paint until about 9 seconds in:

![image](https://cloud.githubusercontent.com/assets/110953/25584744/1a3ee8c4-2e4c-11e7-9085-ec10de52a861.png)

https://www.webpagetest.org/video/compare.php?tests=170501_97_ba8c5bf5efc877719f267f8011498293-r:2-c:0

If we dig into the waterfall we can see that quite a few of your critical path requests are taking a while to get fetched, pushing out the point when all of the JS gets fetched, parsed and executed.

![image](https://cloud.githubusercontent.com/assets/110953/25584774/3f0a50c6-2e4c-11e7-95cf-bcee2924bcc3.png)

Looking at the source you're using prefetch instead of preload here:

![image](https://cloud.githubusercontent.com/assets/110953/25584811/6611049e-2e4c-11e7-977c-d2678d73aee0.png)

This will actually force your scripts to be loaded with a _lower_ priority than if you use preload. I would strongly reco trying to use `preload` for these here.

Your total amount of JS in the app is relatively small. Still way under 100KB from what I can see.

**Comment by addyosmani** [comment]
On faster 3G (optimistic connection), you're doing a lot better here: https://www.webpagetest.org/video/compare.php?tests=170501_BW_5392eef343fcefe55b9c7c61ffa3301e-r:3-c:0 interactive in under 5 seconds from what I can see https://www.webpagetest.org/result/170501_BW_5392eef343fcefe55b9c7c61ffa3301e/1/details/#waterfall_view_step1. This is awesome. 

I think it can be made faster though :)

**Comment by grgur** [comment]
Thanks @addyosmani 

A few quick fixes and it looks a whole lot better.
* prefetch replaced with preload for JS content
* css is preloaded, too
* GitHub API for Star/Fork buttons is now injected after the icons are loaded

Renders in about 5 seconds on EM now
![image](https://cloud.githubusercontent.com/assets/733074/25586178/7d80add0-2e9e-11e7-93f9-3229250026fb.png)

Waterfall looks better, too
![image](https://cloud.githubusercontent.com/assets/733074/25586196/952c17a8-2e9e-11e7-8cb3-085a403b275b.png)

**Comment by addyosmani** [comment]
This looks awesome. Ship it! :D

**Comment by grgur** [comment]
Shipped 😆 https://budgeting-a937b.firebaseapp.com/budget

**Comment by addyosmani** [comment]
\o/
