### ISSUE TITLE
[Question] Why core module is on low priority?

### ISSUE THREAD

**Issue by iNikNik** [ModusCreateOrg/budgeting-sample-app-webpack2#56]
Does it make sense to pre-load resources with higher priority than main module?
It should affect on time to interactive.. isn't it?

![image](https://cloud.githubusercontent.com/assets/7679749/25738108/f5803d36-3183-11e7-9ad3-e05febc95b59.png)

And the second question is - It seems like 'reports.js' is downloaded twice:

![image](https://cloud.githubusercontent.com/assets/7679749/25738405/9678bdfc-3185-11e7-91e5-0284d33b25cf.png)

Can you help me to figure it out, please?

PS I'm using chrome with cache enabled; `yarn run prod`

**Comment by iNikNik** [comment]
If there is no way to change the priority of preload - we should definitely start these after core is loaded

**Comment by grgur** [comment]
main.js should have come preloaded. That was a bug, thank you for pointing it out. It's been fixed and it loads in higher priority now. 
![image](https://cloud.githubusercontent.com/assets/733074/25796644/99e86d6e-33da-11e7-8c6b-dd754d10767e.png)

![image](https://cloud.githubusercontent.com/assets/733074/25796861/6f56a18c-33db-11e7-8776-789b3aa00278.png)


As for the reports bundle being re-downloaded, I'm afraid I can't reproduce that on the [deployed site](https://budgeting-a937b.firebaseapp.com/budget)
