### ISSUE TITLE
`screw_ie8` is not a supported option

### ISSUE THREAD

**Issue by Dante-101** [ModusCreateOrg/budgeting-sample-app-webpack2#57]
On the current master branch, I end up with this error when I run `npm run build`.
```
ERROR in main-ee2fb0ea.js from UglifyJs
DefaultsError: `screw_ie8` is not a supported option
```

**Comment by grgur** [comment]
Fixed UglifyJS version in https://github.com/ModusCreateOrg/budgeting-sample-app-webpack2/pull/60

Thanks for reporting!
