### ISSUE TITLE
Cannot find module './dll/d3-manifest.json'

### ISSUE THREAD

**Issue by danjonescidtrix** [ModusCreateOrg/budgeting-sample-app-webpack2#62]
After cloning the project and installing the dependencies, when I run "npm start" I get:

> Cannot find module './dll/d3-manifest.json'

is this a problem on my end or the project?
Thank you in advance!

**Comment by grgur** [comment]
Weird. It should have been created on postinstall. Can you try `npm run dll` please?

**Comment by danjonescidtrix** [comment]
That seems to have fixed it, many thanks! @grgur
