### ISSUE TITLE
Missing example for multiple query definitions for new loader syntax

### ISSUE THREAD

**Issue by Sawtaytoes** [ModusCreateOrg/budgeting-sample-app-webpack2#7]
It's common to see loaders like this in Webpack 1:

``` jsx
loaders: [
    'isomorphic-style'
    'css?sourceMap'
    'postcss?sourceMap'
    'sass?sourceMap'
]
```

This example isn't represented in this Webpack's config file.
Is that out of the scope of this sample project or is it something you're considering adding?

**Comment by grgur** [comment]
I just updated the app to match the latest specs. 
For details on how loaders, rules, and queries are used in Webpack 2, I suggest you see the official [migration guide](https://webpack.js.org/how-to/upgrade-from-webpack-1/)
